name: CI - Docker Build and Push

on:
  push:
    branches: ['**']  # Triggers on push to any branch
  pull_request:
    branches: [ '**' ]  # Triggers on PRs targeting any branch

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set lowercase repository name
        run: echo "REPO_LOW=$(echo '${{ github.repository }}' | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true  # Push on every branch
          tags: |
            ghcr.io/${{ env.REPO_LOW }}:${{ github.ref_name }}
            ghcr.io/${{ env.REPO_LOW }}:sha-${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          build-args: |
            NODE_ENV=production

      # Tag as 'latest' only on main branch
      - name: Tag as latest (main branch only)
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        run: |
          docker buildx imagetools create \
            ghcr.io/${{ env.REPO_LOW }}:${{ github.ref_name }} \
            --tag ghcr.io/${{ env.REPO_LOW }}:latest

      - name: Verify Image Push
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        run: |
          sleep 10
          if curl -s -f "https://ghcr.io/v2/${{ env.REPO_LOW }}/manifests/latest" > /dev/null; then
            echo "✅ Image pushed and accessible!"
          else
            echo "❌ Push verification failed!"
            exit 1
          fi

      - name: Build Summary
        if: always()
        run: |
          echo "## Build Results 🐳" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "- **Status:** ${{ job.status }}" >> $GITHUB_STEP_SUMMARY
          echo "- **Branch:** ${{ github.ref_name }}" >> $GITHUB_STEP_SUMMARY
          echo "- **Commit:** ${{ github.sha }}" >> $GITHUB_STEP_SUMMARY
          if [[ "${{ github.ref }}" == "refs/heads/main" && "${{ github.event_name }}" == "push" ]]; then
            echo "- **Image Tags:**" >> $GITHUB_STEP_SUMMARY
            echo "  - \`ghcr.io/${{ env.REPO_LOW }}:latest\`" >> $GITHUB_STEP_SUMMARY
            echo "  - \`ghcr.io/${{ env.REPO_LOW }}:sha-${{ github.sha }}\`" >> $GITHUB_STEP_SUMMARY
          fi

      - name: Notify on failure
        if: failure()
        run: |
          echo "❌ Docker build or push failed! Check logs above."